language: c++
compiler: gcc
sudo: true

matrix:
  include:

  - os: osx
    env: 
      - TARGET="osx"
      - HOMEBREW_NO_AUTO_UPDATE=1
      - MATRIX_EVAL="brew install gcc && CC=gcc && CXX=g++"

  - os: osx
    compiler: clang
    env: 
      - TARGET="osx"
      - MATRIX_EVAL="CC=clang && CXX=clang++"

  - os: windows
    language: go
    compiler: mingw
    env: TARGET="win"

before_install:
  - eval "${MATRIX_EVAL}"

  - if [ ! -d platform/$TARGET/src ]; then
      mkdir platform/$TARGET/src;
    fi

  - if [ -f override.sh ]; then
      chmod +x override.sh;
    fi

  - if [ -f platform/$TARGET/install.sh ]; then
      chmod +x platform/$TARGET/install.sh;
    fi

  - if [ "$TARGET" = "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
      sudo apt-get install -qq g++-7;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 50;
    fi

install:
  - if [ -f platform/$TARGET/install.sh ]; then
      platform/$TARGET/install.sh;
    fi
    
before_script:
  - if [ -f platform/$TARGET/build.sh ]; then
      chmod +x platform/$TARGET/build.sh;
    fi

script:
  - if [ -f platform/$TARGET/build.sh ]; then
      platform/$TARGET/build.sh;
    fi
