language: c++
compiler: gcc
sudo: true

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env: 
    - TARGET="linux"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


  - os: linux
    compiler: clang
    dist: trusty
    sudo: required
    addons:
      apt:
        sources: 
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - clang-6.0
    env: 
    - TARGET="linux"
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"


  - os: osx
    env: 
    - TARGET="osx"
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MATRIX_EVAL="brew install gcc && CC=gcc && CXX=g++"


  - os: osx
    compiler: clang
    env: 
    - TARGET="osx"
    - MATRIX_EVAL="CC=clang && CXX=clang++"


  - os: windows
    language: go
    env:
    - TARGET="win"
    - MATRIX_EVAL="CC=gcc && CXX=g++ && MAKE=mingw32-make"


install:
  - eval "${MATRIX_EVAL}"

  - if [ -f platform.sh ]; then
      chmod +x platform.sh;
      platform.sh;
    fi

  - if [ -f platform/$TARGET/install.sh ]; then
      chmod +x platform/$TARGET/install.sh;
      platform/$TARGET/install.sh;
    fi
    
  - if [ -d platform/$TARGET/source ]; then
      mv -f platform/$TARGET/source/* source;
    fi


script:
  - if [ -f platform/$TARGET/build.sh ]; then
      chmod +x platform/$TARGET/build.sh;
      platform/$TARGET/build.sh;
    fi
